create table banking_case(Client_ID varchar(50),
Name varchar(50),
Age int,
Location_ID varchar(50),
Joined_Bank DATE,
Banking_Contact varchar(50),
Nationality varchar(50),
Occupation varchar(70),
Fee_Structure varchar(25),
Loyalty_Classification varchar(50),
Estimated_Income int,	
Superannuation_Savings int,
Amount_of_Credit_Cards	int, 
Credit_Card_Balance	int,
Bank_Loans int,
Bank_Deposits int,
Checking_Accounts int,
Saving_Accounts int,
Foreign_Currency_Account int,
Business_Lending int,
Properties_Owned int,
Risk_Weighting int,
BRId int,
GenderId int,
IAId int)

select * from banking_case